---

- name: Playbook to manage aidanjgriffiths dotfiles
  hosts: localhost
  connection: local
  roles:
    - role: nvim
      tags:
        - nvim
    - role: tmux
      tags:
        - tmux
    - role: miniconda
      tags:
        - miniconda
    - role: zsh
      tags:
        - zsh
