---

- name: Install  with Homebrew in macOS
  include_tasks: macos.yml
  when: ansible_distribution == "MacOSX"

- name: Install  with dnf in Fedora
  include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.local/share/oh-my-zsh
    single_branch: yes
    update: yes

- name: Create a symbolic to zshrc
  ansible.builtin.file:
    src: "{{ playbook_dir }}/zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: yes  # need to force in case .zshrc exists

- name: Make sure ~/.zsh exists
  ansible.builtin.file:
    path: ~/.zsh
    state: directory
    mode: '0755'

- name: Install conda-zsh-completion
  ansible.builtin.git:
    repo: https://github.com/esc/conda-zsh-completion.git
    dest: ~/.zsh/conda-zsh-completion
    single_branch: yes
    update: yes

- name: Stow zsh plugin files
  shell: "stow .zsh --target {{ ansible_env.HOME }}/.zsh"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'

- name: Create a symbolic to zshrc
  ansible.builtin.file:
    src: "{{ playbook_dir }}/zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: yes  # need to force in case .zshrc exists

- name: Initialise conda
  shell: "conda init zsh"
  register: result
  changed_when: 'result.stderr is search("modified")'
